#!/bin/sh
# Initial script for Linux Live Kit
# Author: Tomas M <http://www.linux-live.org/>

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

. /lib/.config
. /lib/livekitlib

#transfer_initramfs

MEMORY=/memory
CHANGES=$MEMORY/changes
UNION=$MEMORY/union
SQUASHFSFILECONTAINERMNT=$MEMORY/datacontainer
ROOTCONTAINERMNT=$MEMORY/rootcontainer

header "Live Kit init <http://www.linux-live.org/>"

init_proc_sysfs

debug_start
debug_shell

init_devs
#init_aufs
#init_zram

modprobe ata_piix
modprobe sd_mod
debug_shell

# find data dir with filesystem bundles
#DATA="$(find_data 60 "$DATAMNT")"
#DATA="$(find_data 10 "$DATAMNT")"
modprobe ext3
mkdir "$SQUASHFSFILECONTAINERMNT"
mount /dev/sda1 "$SQUASHFSFILECONTAINERMNT"
mkdir "$ROOTCONTAINERMNT"
mount "$SQUASHFSFILECONTAINERMNT/$LIVEKITNAME/squashRootfs" "$ROOTCONTAINERMNT" -o loop
losetup /dev/loop1 "$ROOTCONTAINERMNT/rootfs"
debug_shell

# setup persistent changes, if possible
#persistent_changes "$DATA" "$CHANGES"

# 出现readonly 系统死机的状况
#dd if=/dev/zero of=cowfile.out bs=1M seek=200 count=0
#losetup /dev/loop2 cowfile.out
#debug_shell

modprobe ext2
modprobe dm-mod
mkdir "$UNION"
#echo "0 `blockdev --getsize /dev/loop1` snapshot /dev/loop1 /dev/loop2 p 32" | dmsetup create cow
echo "0 `blockdev --getsize /dev/loop1` snapshot /dev/loop1 /dev/sdb p 32" | dmsetup create cow
mount /dev/mapper/cow "$UNION"
debug_shell

# copy to RAM if needed
#DATA="$(copy_to_ram "$DATA" "$CHANGES")"
#debug_shell

# init aufs union
#init_union "$CHANGES" "$UNION"
#debug_shell

# add data to union
#union_append_bundles "$DATA" "$BUNDLES" "$UNION"
#debug_shell


# rootcopy
#copy_rootcopy_content "$DATA" "$UNION"

# create empty fstab
fstab_create "$UNION"
debug_shell

header "Live Kit done, starting $LIVEKITNAME"
change_root "$UNION"

header "!!ERROR occured, you shouldn't be here.!!"
/bin/sh
